name: Build Kadoor App
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # ارتقا به نسخه ۴
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - run: flutter pub get
      
      - run: flutter build apk --split-per-abi
      
      - name: Upload APK
        uses: actions/upload-artifact@v4 # تغییر اصلی اینجاست (v4)
        with:
          name: kadoor-android-app
          path: build/app/outputs/flutter-apk/app-release.apk
